-- PHOENIX HUB - WATCH PARTY YOUTUBE V1
create extension if not exists pgcrypto;
create table if not exists public.watch_rooms(
 id uuid primary key default gen_random_uuid(), name text not null check(char_length(name) between 2 and 50), youtube_id text not null check(char_length(youtube_id)=11), host_member_id uuid not null references public.members(id) on delete cascade, password_hash text, playback_status text not null default 'paused' check(playback_status in('paused','playing')), playback_position double precision not null default 0, playback_updated_at timestamptz not null default now(), expires_at timestamptz not null, is_closed boolean not null default false, created_at timestamptz not null default now());
alter table public.watch_rooms enable row level security;
drop policy if exists "No direct watch room access" on public.watch_rooms;
create policy "No direct watch room access" on public.watch_rooms for all to authenticated using(false) with check(false);
create or replace function public.list_watch_rooms() returns table(id uuid,name text,youtube_id text,host_name text,has_password boolean,expires_at timestamptz,is_host boolean) language sql stable security definer set search_path=public,auth as $$ select w.id,w.name,w.youtube_id,m.display_name,(w.password_hash is not null),w.expires_at,(w.host_member_id=public.current_member_id()) from public.watch_rooms w join public.members m on m.id=w.host_member_id where public.current_member_id() is not null and not w.is_closed and w.expires_at>now() order by w.created_at desc $$;
create or replace function public.create_watch_room(room_name text,youtube_video_id text,room_password text default '',duration_minutes integer default 180) returns jsonb language plpgsql security definer set search_path=public,auth as $$ declare mid uuid; rid uuid; begin mid:=public.current_member_id(); if mid is null then raise exception 'Bạn chưa phải thành viên được duyệt.'; end if; if char_length(trim(room_name))<2 or char_length(trim(room_name))>50 then raise exception 'Tên phòng phải từ 2 đến 50 ký tự.'; end if; if youtube_video_id !~ '^[A-Za-z0-9_-]{11}$' then raise exception 'Video YouTube không hợp lệ.'; end if; rid:=gen_random_uuid(); insert into public.watch_rooms(id,name,youtube_id,host_member_id,password_hash,expires_at) values(rid,trim(room_name),youtube_video_id,mid,case when trim(coalesce(room_password,''))='' then null else crypt(room_password,gen_salt('bf')) end,now()+make_interval(mins=>greatest(30,least(coalesce(duration_minutes,180),1440)))); return jsonb_build_object('ok',true,'id',rid); end $$;
create or replace function public.join_watch_room(target_room_id uuid,room_password text default '') returns jsonb language plpgsql security definer set search_path=public,auth as $$ declare mid uuid; w public.watch_rooms%rowtype; hn text; begin mid:=public.current_member_id(); if mid is null then raise exception 'Bạn chưa phải thành viên được duyệt.'; end if; select * into w from public.watch_rooms where id=target_room_id and not is_closed and expires_at>now(); if not found then raise exception 'Phòng không tồn tại hoặc đã hết hạn.'; end if; if w.password_hash is not null and w.password_hash<>crypt(coalesce(room_password,''),w.password_hash) then raise exception 'Mật khẩu phòng không đúng.'; end if; select display_name into hn from public.members where id=w.host_member_id; return jsonb_build_object('ok',true,'is_host',w.host_member_id=mid,'room',jsonb_build_object('id',w.id,'name',w.name,'youtubeId',w.youtube_id,'hostName',hn,'status',w.playback_status,'position',w.playback_position,'updatedAt',w.playback_updated_at)); end $$;
create or replace function public.update_watch_state(target_room_id uuid,new_status text,new_position double precision) returns jsonb language plpgsql security definer set search_path=public,auth as $$ declare mid uuid; w public.watch_rooms%rowtype; begin mid:=public.current_member_id(); if new_status not in('playing','paused') then raise exception 'Trạng thái không hợp lệ.'; end if; update public.watch_rooms set playback_status=new_status,playback_position=greatest(0,coalesce(new_position,0)),playback_updated_at=now() where id=target_room_id and host_member_id=mid and not is_closed and expires_at>now() returning * into w; if not found then raise exception 'Chỉ host mới điều khiển video.'; end if; return jsonb_build_object('ok',true,'state',jsonb_build_object('status',w.playback_status,'position',w.playback_position,'updatedAt',w.playback_updated_at)); end $$;
create or replace function public.close_watch_room(target_room_id uuid) returns jsonb language plpgsql security definer set search_path=public,auth as $$ begin update public.watch_rooms set is_closed=true where id=target_room_id and host_member_id=public.current_member_id() and not is_closed; if not found then raise exception 'Chỉ host mới được đóng phòng.'; end if; return jsonb_build_object('ok',true); end $$;
grant execute on function public.list_watch_rooms() to authenticated;
grant execute on function public.create_watch_room(text,text,text,integer) to authenticated;
grant execute on function public.join_watch_room(uuid,text) to authenticated;
grant execute on function public.update_watch_state(uuid,text,double precision) to authenticated;
grant execute on function public.close_watch_room(uuid) to authenticated;
